version: "3"
output: interleaved
dotenv: [".env.local"]

tasks:
  post_create_sandbox:
    desc: "Runs after this template is instantiated as a Sandbox or Bootstrap"
    cmds:
      - echo -e "To setup and run the agent:\n"
      - echo -e "    cd {{.ROOT_DIR}}"
      - echo -e "    pnpm install"
      - echo -e "    pnpm build"
      - echo -e "    node dist/agent.js start\n"

  install_sandbox:
    desc: "Bootstrap application for local development"
    cmds:
      - "pnpm install"
